"""mac/gitrunner's GitHub credential: a GitHub App's private key mints one-hour installation tokens on demand
(JWT, installation lookup, cache, refresh), the stored PAT is the fallback, and set-app / set-token switch between
them with a way back. Run on Linux with a stand-in curl that answers the GitHub API from files; the key is a
throwaway generated by openssl for the session, never a real one."""

import base64
import json
import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest
from appkeys import OPENSSL, b64url_decode, make_keys, verify_jwt

pytestmark = pytest.mark.skipif(OPENSSL is None, reason="openssl not installed")

ROOT = Path(__file__).resolve().parent.parent
GITRUNNER = ROOT / "mac" / "gitrunner"
NOW = 1_800_000_000  # 2027-01-15T08:00:00Z
ISO = "2027-01-15T08:59:50Z"  # what GitHub would say for a token minted at NOW (an hour, less a little)
EXPIRES = 1_800_003_590

# Answers the GitHub API calls gitrunner makes. Logs every call (arguments and the header it was sent, which the
# tests read to see what authenticated it); `-H @-` is read from stdin like curl does.
CURL = r"""#!/bin/bash
out=""; url=""; method=GET; hdr=""
while [ $# -gt 0 ]; do
  case "$1" in
    -H) case "$2" in @-) hdr="$hdr$(cat)"$'\n' ;; @*) hdr="$hdr$(cat "${2#@}")"$'\n' ;; esac; shift 2 ;;
    -X) method=$2; shift 2 ;;
    -o) out=$2; shift 2 ;;
    -m|--data) shift 2 ;;
    -*) shift ;;
    *) url=$1; shift ;;
  esac
done
path=${url#https://api.github.com/}
echo "ARGV $method $url" >> "$STUB_DIR/argv.log"
echo "CALL $method $path :: $(printf '%s' "$hdr" | tr '\n' ' ')" >> "$STUB_DIR/calls.log"
[ -e "$STUB_DIR/offline" ] && exit 7
case "$method $path" in
  "GET orgs/example-org/installation")
    [ -e "$STUB_DIR/no_installation" ] && exit 22
    echo '{"id": 777, "account": {"login": "example-org", "id": 99}}' ;;
  "POST app/installations/"*"/access_tokens")
    id=${path#app/installations/}; id=${id%/access_tokens}
    [ "$id" = 777 ] || exit 22
    [ -e "$STUB_DIR/no_token" ] && exit 22
    n=$(cat "$STUB_DIR/minted" 2>/dev/null || echo 0); n=$((n + 1)); echo "$n" > "$STUB_DIR/minted"
    printf '{\n  "token": "ghs_FAKE%s",\n  "expires_at": "%s"\n}\n' "$n" "$(cat "$STUB_DIR/iso")" ;;
  "GET orgs/example-org/actions/runners?per_page=1")
    [ -e "$STUB_DIR/list_fails" ] && exit 22
    echo '{"total_count": 0, "runners": []}' ;;
  *) exit 22 ;;
esac
"""

STUBS = {
    "curl": CURL,
    "id": '#!/bin/sh\ncase "$1" in -u) echo 0 ;; _*) exit 0 ;; *) /usr/bin/id "$@" ;; esac\n',
}


@pytest.fixture(scope="session")
def keys(tmp_path_factory):
    pkcs1, pkcs8, pub = make_keys(tmp_path_factory.mktemp("keys"))
    return {"pkcs1": pkcs1, "pkcs8": pkcs8, "pub": pub}


class Box:
    def __init__(self, tmp_path, keys):
        self.t = tmp_path
        self.keys = keys
        self.home = tmp_path / "home"
        self.home.mkdir()
        self.bin = tmp_path / "bin"
        self.bin.mkdir()
        for name, body in STUBS.items():
            (self.bin / name).write_text(body)
            (self.bin / name).chmod(0o755)
        (tmp_path / "iso").write_text(ISO)
        self.env = {
            **os.environ,
            "PATH": f"{self.bin}:{os.environ['PATH']}",
            "GITRUNNER_HOME": str(self.home),
            "GITRUNNER_LOGS": str(tmp_path / "logs"),
            "GITRUNNER_NOW": str(NOW),
            "STUB_DIR": str(tmp_path),
        }
        # the functions only: everything above the script's command dispatch
        (tmp_path / "gr.sh").write_text(GITRUNNER.read_text().split("\ncmd=${1:-help}")[0])

    def install_app(self, app_id="12345", key="pkcs1"):
        (self.home / "github-app.id").write_text(app_id + "\n")
        shutil.copy(self.keys[key], self.home / "github-app.pem")

    def install_pat(self, token="pat123"):
        (self.home / "github-auth.header").write_text(f"Authorization: Bearer {token}\n")

    def flag(self, name):
        (self.t / name).write_text("")

    def sh(self, script, **env):
        return subprocess.run(
            ["bash", "-c", f"source {self.t / 'gr.sh'}; {script}"],
            env={**self.env, **env},
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
        )

    def cli(self, *args, **env):
        return subprocess.run(
            ["bash", str(GITRUNNER), *args],
            env={**self.env, **env},
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
        )

    def calls(self):
        f = self.t / "calls.log"
        return f.read_text().splitlines() if f.exists() else []

    def minted(self):
        f = self.t / "minted"
        return int(f.read_text()) if f.exists() else 0

    def set_app(self, key="pkcs1", app_id="12345", **env):
        b64 = subprocess.run(
            [OPENSSL, "base64", "-A", "-in", str(self.keys[key])], capture_output=True, text=True, check=True
        ).stdout
        return self.cli("set-app", "example-org", NEW_APP_ID=app_id, NEW_APP_KEY_B64=b64, **env)


@pytest.fixture
def box(tmp_path, keys):
    return Box(tmp_path, keys)


def jwt_of(call):
    return call.split("Bearer ")[1].split()[0]


def test_jwt_is_rs256_with_the_right_claims_and_verifies_with_the_public_key(box):
    box.install_app()
    r = box.sh("app_jwt")
    assert r.returncode == 0, r.stderr
    head, body, _ = r.stdout.split(".")
    assert json.loads(b64url_decode(head)) == {"alg": "RS256", "typ": "JWT"}
    assert json.loads(b64url_decode(body)) == {"iat": NOW - 60, "exp": NOW + 540, "iss": 12345}
    assert "=" not in r.stdout and "+" not in r.stdout and "/" not in r.stdout  # base64url, unpadded
    assert verify_jwt(r.stdout, box.keys["pub"], box.t)


def test_pkcs8_key_signs_too_and_a_client_id_is_a_string_issuer(box):
    box.install_app(app_id="Iv1.abc123", key="pkcs8")
    r = box.sh("app_jwt")
    assert r.returncode == 0, r.stderr
    assert json.loads(b64url_decode(r.stdout.split(".")[1]))["iss"] == "Iv1.abc123"
    assert verify_jwt(r.stdout, box.keys["pub"], box.t)


def test_garbage_key_fails_without_printing_a_token(box):
    box.install_app()
    (box.home / "github-app.pem").write_text("not a key\n")
    r = box.sh("gh_api GET orgs/example-org/actions/runners?per_page=1")
    assert r.returncode != 0 and "valid RSA key" in r.stderr
    assert box.calls() == []


def test_installation_is_looked_up_once_and_the_token_minted_once_and_reused(box):
    box.install_app()
    r = box.sh(
        "gh_api GET 'orgs/example-org/actions/runners?per_page=1'; gh_api GET 'orgs/example-org/actions/runners?per_page=1'"
    )
    assert r.returncode == 0, r.stderr
    kinds = [c.split(" :: ")[0] for c in box.calls()]
    assert kinds == [
        "CALL GET orgs/example-org/installation",
        "CALL POST app/installations/777/access_tokens",
        "CALL GET orgs/example-org/actions/runners?per_page=1",
        "CALL GET orgs/example-org/actions/runners?per_page=1",
    ]
    calls = box.calls()
    # the lookup and the mint are authenticated by a JWT that verifies; the runner calls carry the installation token
    assert verify_jwt(jwt_of(calls[0]), box.keys["pub"], box.t)
    assert verify_jwt(jwt_of(calls[1]), box.keys["pub"], box.t)
    assert "Bearer ghs_FAKE1" in calls[2] and "Bearer ghs_FAKE1" in calls[3]
    assert (box.home / "github-app.installation").read_text().strip() == "777"
    assert (box.home / "github-app-token.expires").read_text().strip() == f"{EXPIRES} {ISO}"


def test_no_credential_ever_reaches_a_command_line(box):
    box.install_app()
    box.sh("gh_api GET 'orgs/example-org/actions/runners?per_page=1'")
    argv = (box.t / "argv.log").read_text()
    assert "Bearer" not in argv and "ghs_" not in argv and "eyJ" not in argv


def test_credential_files_are_private(box):
    box.install_app()
    box.sh("app_ensure")
    for name in ("github-app.installation", "github-app-token.header", "github-app-token.expires"):
        assert stat.S_IMODE((box.home / name).stat().st_mode) == 0o600, name


def test_token_is_reused_until_ten_minutes_before_expiry_then_refreshed(box):
    box.install_app()
    assert box.sh("app_ensure").returncode == 0 and box.minted() == 1
    assert box.sh("app_ensure", GITRUNNER_NOW=str(EXPIRES - 601)).returncode == 0 and box.minted() == 1  # still good
    assert (
        box.sh("app_ensure", GITRUNNER_NOW=str(EXPIRES - 599)).returncode == 0 and box.minted() == 2
    )  # inside the margin
    assert "ghs_FAKE2" in (box.home / "github-app-token.header").read_text()
    assert sum(1 for c in box.calls() if c.startswith("CALL GET orgs/example-org/installation")) == 1  # id stays cached


def test_an_expired_or_unreadable_cache_mints_again(box):
    box.install_app()
    box.sh("app_ensure")
    (box.home / "github-app-token.expires").write_text("garbage\n")
    assert box.sh("app_ensure").returncode == 0 and box.minted() == 2


def test_a_stale_installation_id_is_looked_up_again(box):
    box.install_app()
    (box.home / "github-app.installation").write_text("111\n")  # the App was reinstalled since
    r = box.sh("app_ensure")
    assert r.returncode == 0, r.stderr
    assert (box.home / "github-app.installation").read_text().strip() == "777"
    assert box.minted() == 1


def test_missing_installation_or_failed_mint_fails_cleanly(box):
    box.install_app()
    box.flag("no_installation")
    r = box.sh("gh_api GET 'orgs/example-org/actions/runners?per_page=1'")
    assert r.returncode != 0
    (box.t / "no_installation").unlink()
    box.flag("no_token")
    assert box.sh("app_ensure").returncode != 0
    assert not (box.home / "github-app-token.header").exists()


def test_without_an_app_key_the_stored_pat_is_used_exactly_as_before(box):
    box.install_pat("pat123")
    r = box.sh("gh_api GET 'orgs/example-org/actions/runners?per_page=1'; echo kind=$(credential_kind)")
    assert r.returncode == 0, r.stderr
    assert "kind=pat" in r.stdout
    assert [c.split(" :: ")[0] for c in box.calls()] == ["CALL GET orgs/example-org/actions/runners?per_page=1"]
    assert "Bearer pat123" in box.calls()[0]


def test_with_both_the_app_wins(box):
    box.install_pat("pat123")
    box.install_app()
    r = box.sh("gh_api GET 'orgs/example-org/actions/runners?per_page=1'; echo kind=$(credential_kind)")
    assert "kind=app" in r.stdout
    assert "Bearer ghs_FAKE1" in box.calls()[-1] and "pat123" not in " ".join(box.calls())


def test_no_credential_at_all_fails(box):
    r = box.sh("gh_api GET 'orgs/example-org/actions/runners?per_page=1' || true; echo kind=$(credential_kind)")
    assert "kind=none" in r.stdout and "no GitHub credential" in r.stderr
    assert not box.sh("have_credential").returncode == 0


def test_status_line_names_the_credential(box):
    r = box.sh("credential_line example-org")
    assert r.stdout.strip().startswith("none")
    box.install_pat()
    # the PAT's expiry comes from a response header the stand-in does not send: "never"
    assert box.sh("credential_line example-org").stdout.strip() == "GitHub token stored, expires never"
    box.install_app()
    assert box.sh("credential_line example-org").stdout.strip() == f"GitHub App 12345, token valid until {ISO}"
    box.flag("no_token")
    (box.home / "github-app-token.expires").unlink()
    assert "no token can be minted" in box.sh("credential_line example-org").stdout


def test_set_app_stores_checks_and_replaces_the_pat(box):
    box.install_pat("pat123")
    r = box.set_app()
    assert r.returncode == 0, r.stdout + r.stderr
    assert "now mints GitHub App tokens (App 12345" in r.stdout
    assert not (box.home / "github-auth.header").exists()
    assert (box.home / "github-app.id").read_text().strip() == "12345"
    pem = box.home / "github-app.pem"
    assert pem.read_bytes() == box.keys["pkcs1"].read_bytes()
    assert stat.S_IMODE(pem.stat().st_mode) == 0o600
    assert box.minted() == 1
    # nothing secret in the output
    assert "BEGIN" not in r.stdout + r.stderr and "ghs_FAKE" not in r.stdout + r.stderr
    assert list(box.home.glob(".cred.*")) == [] and list(box.home.glob(".app.*")) == []


def test_set_app_failure_brings_the_old_pat_back(box):
    box.install_pat("pat123")
    box.flag("list_fails")  # the new App can mint but cannot list the runners
    r = box.set_app()
    assert r.returncode != 0 and "kept the old credential" in r.stderr
    assert (box.home / "github-auth.header").read_text() == "Authorization: Bearer pat123\n"
    assert sorted(p.name for p in box.home.iterdir()) == ["github-auth.header"]


def test_set_app_failure_brings_the_old_app_back(box):
    box.install_app(app_id="111", key="pkcs8")
    box.sh("app_ensure")
    before = {p.name: p.read_bytes() for p in box.home.iterdir()}
    box.flag("no_token")
    r = box.set_app(app_id="222")
    assert r.returncode != 0
    assert {p.name: p.read_bytes() for p in box.home.iterdir()} == before


def test_set_app_rejects_a_key_that_is_not_pem(box):
    box.install_pat()
    r = box.cli("set-app", "example-org", NEW_APP_ID="1", NEW_APP_KEY_B64=base64.b64encode(b"not a key").decode())
    assert r.returncode != 0
    assert (box.home / "github-auth.header").exists() and not (box.home / "github-app.pem").exists()
    r = box.cli("set-app", "example-org")
    assert r.returncode != 0 and "NEW_APP_ID" in r.stderr


def test_set_token_switches_an_app_device_back_to_a_pat_and_restores_on_failure(box):
    box.install_app()
    box.sh("app_ensure")
    r = box.cli("set-token", "example-org", NEW_GITHUB_TOKEN="newpat")
    assert r.returncode == 0, r.stderr
    assert (box.home / "github-auth.header").read_text() == "Authorization: Bearer newpat\n"
    assert not (box.home / "github-app.pem").exists() and not (box.home / "github-app-token.header").exists()
    assert "Bearer newpat" in box.calls()[-1]  # verified with the PAT, not the App

    box2 = box.t / "second"
    box2.mkdir()
    b = Box(box2, box.keys)
    b.install_app()
    b.sh("app_ensure")
    before = {p.name: p.read_bytes() for p in b.home.iterdir()}
    b.flag("list_fails")
    r = b.cli("set-token", "example-org", NEW_GITHUB_TOKEN="badpat")
    assert r.returncode != 0 and "kept the old credential" in r.stderr
    assert {p.name: p.read_bytes() for p in b.home.iterdir()} == before


def test_the_linux_vm_check_accepts_an_app_key_in_place_of_a_pat():
    text = GITRUNNER.read_text()
    assert "have_credential || die" in text
    assert '[ -s "$AUTH_HEADER" ] || die' not in text


def test_linuxrunner_still_stores_no_token():
    text = (ROOT / "linux" / "linuxrunner").read_text()
    assert "github-app" not in text and "AUTH_HEADER" not in text


@pytest.mark.parametrize("workflow", ["admin.yml", "admin-win.yml"])
def test_admin_workflows_offer_set_app_and_never_echo_the_key(workflow):
    text = (ROOT / ".github" / "workflows" / workflow).read_text()
    assert "- set-app" in text and "- rotate-token" in text  # rotate-token keeps working for the PAT
    assert "secrets.CI_APP_ID" in text and "secrets.CI_APP_PRIVATE_KEY" in text
    # the key's secret is only ever handed to the step as an environment variable, and never printed
    assert [ln.strip() for ln in text.splitlines() if "secrets.CI_APP_PRIVATE_KEY" in ln] == [
        "APP_PRIVATE_KEY: ${{ inputs.action == 'set-app' && secrets.CI_APP_PRIVATE_KEY || '' }}"
    ]
    for ln in text.splitlines():
        if "APP_PRIVATE_KEY" in ln or "NEW_APP_KEY_B64" in ln:
            assert not any(w in ln for w in ('echo "$', 'Write-Host "$', "echo $", "Write-Host $env"))
